const healthConditions = {
    "heart": "Cardiologist",
    "cardio": "Cardiologist",
    "women": "Gynecologist",
    "pregnancy": "Gynecologist",
    "gynaecology": "Gynecologist",
    "bones": "Orthopedic",
    "orthopedic": "Orthopedic",
    "joint pain": "Orthopedic",
    "nerves": "Neurologist",
    "neurology": "Neurologist",
    "brain": "Neurologist",
    "stroke": "Neurologist",
    "cancer": "Oncologist",
    "oncology": "Oncologist",
    "tumor": "Oncologist",
    "skin": "Dermatologist",
    "dermatology": "Dermatologist",
    "rash": "Dermatologist",
    "infection": "Dermatologist",
    "pulmonary": "Pulmonologist",
    "lungs": "Pulmonologist",
    "breathing": "Pulmonologist",
    "asthma": "Pulmonologist",
    "fever": "General Physician",
    "cold": "General Physician",
    "flu": "General Physician",
    "pain": "General Physician",
    "cough": "General Physician"
};
